moved cp of env file to after permissions

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,18 +47,6 @@ jobs:
               sudo mv server server_old
               echo "Renamed server to server_old"
             fi
-
-            # copy env file 
-            if [ -f "/home/${{ secrets.DEPLOY_RUN_AS_USER }}/env/env_admin" ]; then
-              echo "Found env_admin, copying..."
-              sudo cp /home/${{ secrets.DEPLOY_RUN_AS_USER }}/env/env_admin /tmp/admin-deploy-server/.env
-              echo "Checking if .env was created..."
-              ls -la .env
-            else
-              echo "ERROR: env_admin not found!"
-              exit 1
-            fi
-
             # Move new server files from temp location
             sudo mv /tmp/admin-deploy-server server
 
@@ -71,6 +59,17 @@ jobs:
             # Set proper permissions
             sudo chown -R www-data:www-data /var/www/admin/server
             sudo chmod -R 755 /var/www/admin/server
+
+            # copy env file 
+            if [ -f "/home/${{ secrets.DEPLOY_RUN_AS_USER }}/env/env_admin" ]; then
+              echo "Found env_admin, copying..."
+              sudo cp /home/${{ secrets.DEPLOY_RUN_AS_USER }}/env/env_admin /tmp/admin-deploy-server/.env
+              echo "Checking if .env was created..."
+              ls -la .env
+            else
+              echo "ERROR: env_admin not found!"
+              exit 1
+            fi
 
             # Restart server
             USER=${{ secrets.DEPLOY_RUN_AS_USER }}
